config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "ideas#index"
  get 'likes/create'
  get 'likes/destroy'
  resources :ideas do 
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/ability.rb
class Ability
    include CanCan::Ability
  
    def initialize(user)
     
        user ||= User.new 
        if user.is_admin?
            can :manage, :all
        else
          can :read, :all
        end
   
  
      alias_action(:create, :read, :update, :delete, to: :crud)
  
      can :crud, Idea do |idea|
    idea.user == user
      end
  
      can :crud, Review do |review|
        review.user == user
      end
      can :like, Idea do |idea|
        user.present? && idea.user != user
      end
    end
  end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many(:reviews, dependent: :destroy)
    validates(
        :title,presence:true, uniqueness: true
    )
    validates(
        :description,
        presence:{message:"must exist"},
        length:{minimum:10}
    )
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :idea
    belongs_to :user
  
    validates :idea_id, uniqueness: {scope: :user_id}
    
  end
  

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :idea
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ideas,dependent: :destroy
    has_many :reviews, dependent: :nullify
    before_save {self.email = email.downcase}
    validates :username, presence: true,
      uniqueness:{case_sensitive: false},
      length: {minimun: 3, maximum:25}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
      length: {maximum: 105},
      uniqueness: {case_sensitive: false},
      format: {with: VALID_EMAIL_REGEX}
      has_secure_password
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
  
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
    helper_method(:current_user)
    
  
    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
  
    def authenticate_user!
      unless user_signed_in?
        flash[:danger] = "You must sign in or sign up first!"
        redirect_to new_session_path
      end
    end
  end
  

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :set_idea, only: [:edit, :update, :show, :destroy]
    before_action :authorize!, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
      @ideas = Idea.paginate(page: params[:page])
    end
    
    def new
      @idea = Idea.new
    end
    
    def edit
    end
    
    def create
      @idea = Idea.new(idea_params)
      @idea.user = current_user
      if @idea.save
        flash[:success] = "idea was successfully created"
        redirect_to idea_path(@idea)
      else
        render 'new'
      end
    end
    
    def update
      if @idea.update(idea_params)
        flash[:success] = "idea was successfully updated"
        redirect_to idea_path(@idea)
      else
        render 'edit'
      end
    end
    
    def show
        @review=Review.new 
        @likes = @idea.likes.count
        @reviews=@idea.reviews.order(created_at: :desc)
    end
    
    def destroy
      @idea.destroy
      flash[:danger] = "idea was successfully deleted"
      redirect_to ideas_path
    end
    
    private
      def set_idea
        @idea = Idea.find params[:id] 
      end
    
      def idea_params
        params.require(:idea).permit(:title, :description)
      end
    
      def authorize!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @idea)
      end
    
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def create
      idea = Idea.find(params[:idea_id])
      like = Like.new({user: current_user, idea: idea})
  
      if not can?(:like, idea)
        flash[:danger] = "liking your own idea? wow..."
        return redirect_to idea_path(idea)
      end
  
      if like.save
        redirect_to idea_path(idea), notice: "Thanks for liking!"
      else
        redirect_to idea_path(idea), alert: like.errors.full_messages.join(",")
      end
    end
  
    def destroy
      idea = Idea.find params[:idea_id]
      like = Like.find params[:id]
      
      if like.destroy
        redirect_to idea_path(idea), notice: "😦"
      else 
        redirect_to idea_path(idea), alert: like.errors.full_messages.join(",")
      end
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_review, only: [:destroy, :toggle_hidden]
    before_action :authorize!, only: [:edit, :update, :destroy]
   
  
    def create
      @idea = Idea.find(params[:idea_id])
      @review = Review.new review_params
      @review.idea = @idea
      @review.user = current_user
      if @review.save
        redirect_to @idea
      else
        @reviews = @idea.reviews.order(created_at: :desc)
        render root_path
      end
    end
  
    def destroy
        @review=Review.find params[:id]
        if can?(:curd,@review)
        @review.destroy
        redirect_to @review.idea
        else
            head :unauthorized
        end
    end
  
    
  
    private
  
    def review_params
      params.require(:review).permit( :body)
    end
  
    def find_review
      @review = Review.find params[:id]
    end
  
    
  
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:email])
      if user&.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = 'Thank you for signing in!'
        redirect_to root_path
      else
        flash.now[:alert] = 'Wrong email or password!'
        render :new
      end
    end
  
    def destroy
     session[:user_id] = nil
     flash[:notice] = 'Signed out!'
     redirect_to root_path
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user,only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update,:destroy]
    

    def new 
        @user=User.new 
    end 
    
    def create
        @user =User.new(user_params)
        if @user.save 
            session[:user_id]
            flash[:success]="Welcome to the blog #{@user.username}"
            redirect_to root_path
        else 
            render :new
        end 
    end

    
    
    private 
    def user_params 
        params.require(:user).permit(:username,:email,:password)
    end 
    def set_user 
        @user=User.find(params[:id])
    end
    def require_same_user
        if current_user != @user 
            flash[:danger]="You can only edit your own account"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.any?%>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
        <%=pluralize(@idea.errors.count,"error")%>
        prohibited this idea from being saved"
        </h2>
        <div class="panel-body">
          <ul>
            <% @idea.errors.full_messages.each do |msg| %>
            <li><%=msg%></li>
            <% end %>
          </ul>

        </div>

      </div>

    </div>

  </div>
</div>
<% end %>


<div class="row">
  <div class="col-xs-12">

    <%=form_for(@idea, :html => {class:"form-horizontal",role: "form"}) do |f| %>

    <div class="form-group">

      <div class="control-label col-sm-2">
        <%=f.label :title %>
        </div>

        <div class="col-sm-8">
        <%=f.text_field :title, class:"form-control",placeholder:"title",autofocus:true %>
      </div>

      </div>

      <div class="form-group">

        <div class="control-label col-sm-2">
        <%= f.label :description %>
        </div>

        <div class="col-sm-8">
        <%= f.text_area :description,rows:10,class:"form-control",placeholder:"body",autofocus:true %>
        </div>

        </div>

      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class:"btn btn-primary btn-lg"%>
        </div>
        </div>

    <%end%>
    <div class="col-xs-4 col-xs-offset-4">


    [<%=link_to"cancel request and return idea listing",ideas_path %>]
    </div>
  </div>

</div>

app/views/ideas/_idea.html.erb
<% obj.each do |idea| %>

  <div class="row">
  
  <div class="col-xs-8 col-xs-offset-2">
  
  <div class="well well-lg">
  
  <div class="idea-title">
  
  <%= link_to idea.title, idea_path(idea) %>
  
  </div>
  
  <div class="idea-body">
  
  <%= truncate(idea.description, length: 100) %>
  
  <div class="idea-meta-details">
  
  <small>Created by: <%= idea.user.username if idea.user%>,
  
  <%= time_ago_in_words(idea.created_at) %> ago,
  
  last updated: <%= time_ago_in_words(idea.updated_at) %> ago</small>
  
  </div>
  
  </div>
  <% if can? :crud, @idea %>
  <div class="idea-actions">
  
  <%= link_to "Edit this idea", edit_idea_path(idea), class: "btn btn-xs btn-primary" %>
  
  <%= link_to "Delete this idea", idea_path(idea), method: :delete,
  
  data: { confirm: "Are you sure you want to delete the idea?"},
  
  class: "btn btn-xs btn-danger" %>
  
  </div>
  <% end %>
  
  </div>
  
  </div>
  
  </div>
  
  <% end %>

app/views/ideas/edit.html.erb
<h1 align="center">edit existing idea </h1>

<%=render "form"%>

app/views/ideas/index.html.erb
<h1 align="center">Listing all ideas</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'idea', obj: @ideas%>
<div align="center">
  <%= will_paginate %>
</div>

app/views/ideas/new.html.erb
<h1 align="center">create an idea</h1>
<%=render "form"%>

app/views/ideas/show.html.erb
<h2 align="center">Title:<%=@idea.title%></h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @idea.user %>
<ul class="listing">
    <div class ="row center">
    <div class=" col-md-4 col-md-offset-4">
    <li> <%= @idea.created_at %> </li>
    <li>
    Created by: <%= @idea.user&.username || 'DELETED'  %>
    </li>
    
    <li class ="idea-title">
    
    </li>
    
    </div>
    </div>
    </ul>
    <%end%>
    
<h4 class="center description "><strong>Description: </strong></h4>
<hr>
<div class="center">
<%= simple_format(@idea.description)%>
</div>
<hr/>
<div >likes: <%=  @idea.likes.count %></div>
<% like = @idea.likes.find_by(user: current_user) %>
<% if like.present? %>
  <%= link_to "Un-like", idea_like_path(@idea, like), method: :delete%>
<% else %>
  <%= link_to "Like", idea_likes_path(@idea), method: :post%>
<% end %>
<div class="idea-action">
  <% if can? :crud, @idea %>
  <%= link_to "edit this idea",edit_idea_path(@idea),class:"btn btn-xs btn-primary"%>   
  <%= link_to "delete this idea", idea_path(@idea), method: :delete, 
                                    data:{confirm:"are you sure want to delete the idea"}, 
                                    class:"btn btn-xs btn-danger"%>
  <%= link_to "view all ideas",ideas_path,class: "btn btn-xs btn-success" %>
  <% end%>

</div>
</div>
<%= form_with(model: [@idea, @review], local: true) do |f| %>
<% if @review.errors.any? %>
  <ul>
    <% @review.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class=" center form-group well col-xs-8 col-xs-offset-2">
  <%= f.text_area(
  :body,
  cols: 50,
  rows: 5,
  placeholder: "What are your thoughts?",
  class: "form-control"
  ) %>
</div>
<div class="center btn well col-xs-8 col-xs-offset-2"">
<%= f.submit "review" %>
<% end %>
</div>
<hr/>
<div class="center reviews well col-xs-8 col-xs-offset-2"">
<h1><strong>Reviews</strong></h1>
</div>
<ul class=" center well col-xs-8 col-xs-offset-2"">
  <% @reviews.each do |review| %>
      <p>
        <%= review.body %> <br />
        <% if can? :crud, review %>
         <small>
          reviewed <%= time_ago_in_words(review.created_at) %> ago
        </small>
        <small>
          <%= link_to(
            "Delete",
            idea_review_path(@idea, review),
            method: :delete,
            data: {
              confirm: "Are you sure?"
            }
          ) %>
        </small>
       
        <% end %>
       
      </p>
   <hr/>
  <% end %>
</ul>

app/views/layouts/_messages.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-expand-lg navbar-light ">

  <%= link_to "Idea blog", root_path, class: "navbar-brand", id: "logo" %>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav navbar-right">
    <ul class="nav navbar-nav"> 
     
      <li><%= link_to "New Idea", new_idea_path %></li>
      <li><%= link_to "Ideas", ideas_path %></li>
      <ul class="nav navbar-nav ">

<% if can? :crud, @idea %>

<li><%= link_to 'Log out', session_path, method: :delete %></li>

<% else %>

<li><%= link_to 'Log in', new_session_path %></li>

<li><%= link_to 'Sign up', session_path %></li>

<% end %>

</ul>
      </ul>
    </div>
  </div>
</nav>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%=render 'layouts/navigation'%>
    <%=render "layouts/messages"%>
    <div class="container">
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
        <%=pluralize(obj.errors.count,"error")%>
        prohibited this article from being saved"
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%=msg%></li>
            <% end %>
          </ul>

        </div>

      </div>

    </div>

  </div>
</div>
<% end %>

app/views/users/new.html.erb
<h1 align="center">Sign up for Ideas Blog</h1>
<%= render 'shared/errors', obj: @user %>

<div class='row'>

<div class='col-xs-12'>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :username %>

</div>

<div class="col-sm-8">

<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :email %>

</div>

<div class="col-sm-8">

<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :password %>

</div>

<div class="col-sm-8">

<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to ideas listing", ideas_path %> ]

</div>

</div>

</div>